from typing import Callable, Protocol, runtime_checkable


@runtime_checkable
class Trigger(Protocol):
    def on_new_object(self, callback: Callable[[str], None]) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
