"""Schema proposal — gated schema evolution requiring human approval.

Replaces the auto-apply path in schema_diff_agent.  When the diff agent finds
new or relaxed fields, it now creates a SchemaProposal (status=PENDING) rather
than immediately writing a new SchemaVersion.  A human must approve before the
SchemaVersion is activated.

Activation path (external to the pipeline):
    SchemaProposal.status = APPROVED
    → apply_diff(session, active_row, diff, origin_document_id) from schema_diff_agent
    → new SchemaVersion with is_active=True
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class ProposalStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"


@dataclass
class SchemaProposal:
    """A proposed schema change that requires explicit human approval.

    Generated by propose_diff() in schema_diff_agent.  Never auto-applied:
    the pipeline surfaces it in state and callers decide whether to activate it.

    additions      — new field dicts in reference-schema YAML shape
    relaxed_fields — names of existing required fields proposed to become optional
    status         — PENDING until a human approves or rejects
    """

    doc_type: str
    proposed_version: str
    additions: list[dict] = field(default_factory=list)
    relaxed_fields: list[str] = field(default_factory=list)
    origin_document_id: str = ""
    status: ProposalStatus = ProposalStatus.PENDING
    rejection_reason: str | None = None

    @property
    def is_empty(self) -> bool:
        return not self.additions and not self.relaxed_fields

    def to_dict(self) -> dict:
        """Serialise to a plain dict for storage in GraphState (JSON-safe)."""
        return {
            "doc_type": self.doc_type,
            "proposed_version": self.proposed_version,
            "additions": self.additions,
            "relaxed_fields": self.relaxed_fields,
            "origin_document_id": self.origin_document_id,
            "status": self.status.value,
            "rejection_reason": self.rejection_reason,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "SchemaProposal":
        return cls(
            doc_type=d["doc_type"],
            proposed_version=d["proposed_version"],
            additions=d.get("additions", []),
            relaxed_fields=d.get("relaxed_fields", []),
            origin_document_id=d.get("origin_document_id", ""),
            status=ProposalStatus(d.get("status", ProposalStatus.PENDING)),
            rejection_reason=d.get("rejection_reason"),
        )
