from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pipelines.truth_engine.models import TruthReport


class Strategy(str, Enum):
    """Strategies the Resolution Engine can choose after a TruthReport.

    ACCEPT, RETRY, HITL, REJECT, and PROMPT_REFINEMENT are fully executable.
    The remaining strategies are architecture placeholders for future phases.
    """

    ACCEPT = "accept"
    RETRY = "retry"
    HITL = "hitl"
    REJECT = "reject"
    PROMPT_REFINEMENT = "prompt_refinement"  # Phase 5.3 — implemented
    BETTER_RETRIEVAL = "better_retrieval"  # Phase 5.x — not yet implemented
    IMAGE_PREPROCESS = "image_preprocess"  # Phase 5.x — not yet implemented
    MODEL_ESCALATION = "model_escalation"  # Phase 5.x — not yet implemented


@dataclass
class RefinedPrompt:
    """Evidence-driven prompt supplement generated by PromptRefinementStrategy.

    additional_instructions is appended to the base extraction prompt before
    the envelope instruction so the model sees focused guidance on each retry.
    prompt_variant is a canonical slug used by the planner to detect duplicate
    refinement attempts for the same failure pattern.
    """

    additional_instructions: str  # text appended after the base prompt
    refinement_reason: str  # why this refinement was generated (audit)
    prompt_variant: str  # canonical slug for dedup (e.g. "missing_fields:X,Y")
    target_fields: list[str]  # fields the refinement focuses on


@dataclass
class RetryPlan:
    """Describes how the next extraction attempt should differ from the last.

    prompt_strategy drives the extraction path in op_a_retry_node:
      "standard" — same base prompt, different RAG context
      "refined"  — base prompt + RefinedPrompt.additional_instructions

    retrieval_strategy drives the RAG lookup behaviour.
    refinement_reason, prompt_variant, and refinement_history are populated only
    when prompt_strategy == "refined" and carry forward across passes for the planner.
    """

    attempt_number: int
    reason: str
    retrieval_strategy: str  # "similarity_search" | "no_context"
    prompt_strategy: str  # "standard" | "refined"
    refinement_reason: str | None = None
    prompt_variant: str | None = None
    refinement_history: list[str] = field(default_factory=list)


@dataclass
class ExecutionRecord:
    """Immutable record of one autonomous pipeline attempt.

    execution_history is a list of these stored in GraphState. The planner
    reads history on every pass so it can adapt based on past outcomes.

    strategy_metadata carries strategy-specific context for richer history
    inspection and analytics. The full telemetry set per execution:
      strategy           — which strategy was chosen
      directives         — directive labels that drove the strategy
      model_used         — model name used for extraction (None = default)
      retrieval_count    — number of retrieved context chunks
      preprocessing_steps — list of preprocessing op names applied
      confidence_before  — confidence at decision time
      confidence_after   — confidence after execution (None until next pass)
      duration_ms        — wall-clock execution time (None if not measured)
      outcome            — canonical outcome string
    """

    strategy: Strategy
    timestamp: str  # ISO 8601 UTC
    outcome: str  # "accepted" | "retry_scheduled" | "refinement_scheduled" | ...
    confidence_before: float
    confidence_after: float | None  # set only when outcome is final (ACCEPT)
    strategy_metadata: dict = field(default_factory=dict)
    directives: list[str] = field(default_factory=list)  # Directive.value strings
    model_used: str | None = None  # explicit model name when escalated
    retrieval_count: int = 0  # RAG chunks retrieved
    preprocessing_steps: list[str] = field(default_factory=list)
    duration_ms: float | None = None
    evidence_before: dict | None = None  # snapshot of key metrics at decision time
    evidence_after: dict | None = None  # snapshot after execution (filled by next pass)


@dataclass(frozen=True)
class PlannerBundle:
    """Immutable context bundle for ResolutionPlanner.plan().

    Encapsulates every input the planner needs in one object. Frozen to
    prevent accidental mutation after construction.

    remaining_budget is pre-computed by the node (max_retries − retry_count)
    so the planner never needs to know how it was derived.
    """

    truth_report: TruthReport | None
    execution_history: list[ExecutionRecord]
    retry_count: int
    remaining_budget: int


@dataclass
class ResolutionDecision:
    """The planner's complete, strongly-typed downstream decision.

    Every field that a subsequent node, executor, or persistence layer needs
    lives here. No loose routing flags should appear elsewhere in GraphState.
    """

    strategy: Strategy
    reason: str
    requires_human: bool
    retry_plan: RetryPlan | None = None
    execution_history: list[ExecutionRecord] = field(default_factory=list)
    learning_candidate: bool = False
    schema_proposal: dict | None = None  # future: schema discovery trigger
